name: Tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.0, 7.4 ]
        stability: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Setup test .env
        run: |
          cp .env.example .env
          sed -i 's|=gsm|=${{ secrets.KP_ZENZIVA_TYPE }}|g' .env
          sed -i 's|=userkey|=${{ secrets.KP_ZENZIVA_USERKEY }}|g' .env
          sed -i 's|=passkey|=${{ secrets.KP_ZENZIVA_PASSKEY }}|g' .env
          sed -i 's|=62xxxxx|=${{ secrets.KP_ZENZIVA_TEST_PHONE }}|g' .env
          sed -i 's|=https://images.com/image.png|=${{ secrets.KP_ZENZIVA_TEST_FILE }}|g' .env

      - name: Execute tests
        run: vendor/bin/phpunit
